### ISSUE TITLE
Applying attr for the non-availableAnim attributes

### ISSUE THREAD

**Issue by AyanGhatak** [fusioncharts/redraphael#65]
In redraphael, we have a list of availableAnimAttrs e.g. "stroke-opacity", ""stroke-width", etc. Apart from these other attributes are not even applied if asked to animate.

To illustrate the fact, say elem is the concerned element,

`elem.animate({
   path: <Array>,
   'stroke-opacity': <Number>,
   'stroke-dasharray': <Array>,
   'stroke-linecap': <String>
}, <animDuration>)`

As path and 'stroke-opacity' are animatable or to say at present, we have a support for them, gets applied with an animation but for the other two attributes(namely  'stroke-dasharray' and 'stroke-linecap') do not even get applied as:

`elem.attr({
   'stroke-dasharray': <Array>,
   'stroke-linecap': <String>
})`

That is where I suggest some improvement. We do not have code for supporting animation of these attributes, thats fine, but if an user gives it should at least get applied.

**Comment by akash-goswami** [comment]
This is a very required feature since the caller module would not have to take separate care for the non-animatable properties. Advantage if this is fixed properly are more separation of concern and reduced code lines.

**Comment by AyanGhatak** [comment]
Closing the issue after the [PR](https://github.com/fusioncharts/redraphael/commit/b722d884ccb29c7ff58258ce5863695a08367735) is now merged.
